### PR TITLE
popup-summary-face for auto-complete popup

### PR DESCRIPTION
**Pull request by mk0x9**
Before: 
screenshot from 2015-04-03 20 40 24
After:
screenshot from 2015-04-03 20 42 04

### CODE REVIEW

**Comment by donderom** [comment]
Nice!

Could you please choose between the closest predefined jazz-bg+1 and jazz-bg+2 colors instead of "custom" gray19?

**Comment by mk0x9** [comment]
Hmm, I've tried different colours, but almost all of them looks too washed out (popup background is very bright compared to frame's, it's #606060). I'll try different colours from palette again.

jazz-bg+1 is a little bit dark (type signature doesn't have enough contrast againt black font).
jazz-bg+5 is too bright, almost the same as popup background.

screenshot from 2015-04-04 00 59 08

screenshot from 2015-04-04 00 59 28

Can we add something like ``jazz-bg+15 "#303030"``?

**Comment by donderom** [comment]
Ok, I see. Thanks for the screenshots!
Technically it's a foreground so I think adding something like jazz-fg+1 (#303030) won't hurt. And I'm pretty sure this color is already used for the fringe and is hardcoded.

**Comment by mk0x9** [comment]
I also think we should make scrollbar background a little bit lighter. It looks much better with the same ``jazz-fg+1`` IMO. What do you think?

#101010, default
screenshot from 2015-04-04 02 17 03

#303030
screenshot from 2015-04-04 02 12 22

#505050
screenshot from 2015-04-04 02 14 50

**Comment by donderom** [comment]
Sure! Feel free to add the changes for scrollbar into this pull request.

**Comment by mk0x9** [comment]
Done.

screenshot from 2015-04-05 04 44 32 clipped

**Comment by donderom** [comment]
Thanks! :+1:

**Comment by mk0x9** [comment]
Argh, it's not complete yet. Sorry for misleading reply.

I contacted github support and they said they have issues right now with pull requests, working on it now. I'll rebase last changes and create another one PR.

**Pull request merged**
