### PR TITLE
additional popup faces

### PR DESCRIPTION
**Pull request by mk0x9**
Those changes weren't attached to last PR due to bug.

### CODE REVIEW

**Comment by donderom** [comment]
Don't you think blue foreground of the scrollbar looks better on #303030 background?

Also please don't use white color. One of the idea of this color scheme to be low contrast and easy on the eyes (btw orange itself was the most challenging). So there is a predefined set of colors and the combination of different colors should be used for styling the other components.

**Comment by mk0x9** [comment]
Regarding scrollbar — not sure. It's more subtle and blends with background. Less visual noise is better IMO. I can agree on same blue as in background of selected item, though. :-)

Regarding white colour — it's already hard-coded in several places, alongside with black and gray. And it's easy on eyes, it's used only for mouse hover on popup (I don't use mouse that often, but sometimes it happens). Default values is white font on bright blue background, contrast & brightness as high as it could get. I'm just trying to stick to the principle of least surprise here.

**Comment by donderom** [comment]
As for any hardcoded values (white, black) it will be changed eventually. For the `popup-menu-mouse-face` you could try to invert the colors used for "usual" selection (blue and fg).

**Comment by mk0x9** [comment]
Okay, what do you think about this one? :-)

screenshot from 2015-04-05 23 42 19

**Comment by donderom** [comment]
:+1:

**Comment by mk0x9** [comment]
K, good to go.

**Comment by donderom** [comment]
Thanks!

I hope you understand my desire to keep it all similar at least! :)

**Comment by mk0x9** [comment]
Sure, I get it. :-)

**Pull request merged**
